name: "Manual Deploy"

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Which branch do you want to deploy from?"
        required: true
        default: "feature/my-branch"
      environment:
        description: "Deploy to which environment?"
        required: true
        default: "playground"
        type: choice
        options:
          - playground
      validation_only:
        description: "Validation only? (true/false)"
        required: true
        default: "false"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code from the specified branch
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: "${{ github.event.inputs.target-branch }}"
      
      # 2. Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH

      # 3. Confirm sfdx is on PATH
      - name: Check Salesforce CLI version
        run: sfdx --version

      # 4. Decide which environment secret to use
      - name: Select environment auth file
        id: select_env
        run: |
          if [ "${{ github.event.inputs.environment }}" = "playground" ]; then
            echo "${{ secrets.SFDX_AUTH_URL }}" > sfdxurl.txt
            echo "::set-output name=alias::playground"
          fi

      # 5. Authenticate to the chosen Salesforce org
      - name: Authenticate to Salesforce
        run: |
          sfdx auth:sfdxurl:store -f sfdxurl.txt -a ${{ steps.select_env.outputs.alias }}
      
      # 6. Deploy or Validate only
      - name: Deploy to Salesforce
        run: |
          if [ "${{ github.event.inputs.validation_only }}" = "true" ]; then
            echo "Performing validation-only deploy..."
            sfdx force:source:deploy -p force-app --testlevel=RunLocalTests --checkonly
          else
            echo "Performing full deploy..."
            sfdx force:source:deploy -p force-app --testlevel=RunLocalTests
